version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - docker:
          - image: circleci/openjdk:11-browser-legacy
      - maven/test # checkout, build, test, and upload test results
